T/T/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('currency/', include('currency.urls')),
    path('', include('log_in.urls')),
]

T/log_in/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)
from .views import EditView
from .views import RegisterView
from .views import DashbordView


app_name = 'log_in'

urlpatterns = [
    path('register/', RegisterView.register, name='register'),
    path('edit/', EditView.edit, name='edit'),
    path('dashboard/', DashbordView.dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='log_in/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='log_in/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='log_in/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='log_in/password_reset_form.html',
        email_template_name='log_in/password_reset_email.html',
        success_url=reverse_lazy('log_in:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='log_in/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='/password_reset_confirm.html',
        success_url=reverse_lazy('log_in:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='log_in/password_reset_complete.html'), name='password_reset_complete'),
]

T/log_in/models.py
from django.db import models
from django.conf import settings


class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

T/log_in/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

T/log_in/views.py
from django.http import request
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.decorators import login_required

from .forms import UserRegistration, UserEditForm


class DashbordView(View):
    @staticmethod
    @login_required
    def dashboard(request):
        return render(request, 'log_in/dashboard.html', {})

class RegisterView(View):
    @staticmethod
    def register(request):
        if request.method == 'POST':
            form = UserRegistration(request.POST or None)
            if form.is_valid():
                new_user = form.save(commit=False)
                new_user.set_password(
                    form.cleaned_data.get('password')
                )
                new_user.save()
                return render(request, 'log_in/register_done.html')
        else:
            form = UserRegistration()

        context = {
            "form": form
        }
        return render(request, 'log_in/register.html', context=context)

class EditView(View):
    @staticmethod
    @login_required
    def edit(request):
        if request.method == 'POST':
            user_form = UserEditForm(instance=request.user,
                                     data=request.POST)
            if user_form.is_valid():
                user_form.save()
        else:
            user_form = UserEditForm(instance=request.user)
        context = {
            'form': user_form,
        }
        return render(request, 'log_in/edit.html', context=context)

T/log_in/templates/log_in/dashboard.html
{% extends "base/base.html" %}
{% load filters_and_tags %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<br>
<a href="{% url 'log_in:edit' %}" class="btn btn-primary">Edit Your Profile</a> or
<a href="{% url 'log_in:password_change' %}" class="btn btn-warning">Change your password</a>
<hr>
{% endblock content %}

T/log_in/templates/log_in/edit.html
{% extends "base/base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

T/log_in/templates/log_in/logged_out.html
{% extends "base/base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
<h1>Logged out</h1>
<p>
    You have been successfully logged out.
    <hr>
    You can <a href="{% url 'log_in:login' %}">log-in again</a>.
</p>
{% endblock %}

T/log_in/templates/log_in/password_change_form.html
{% extends "base/base.html" %}
{% load bootstrap4 %}
{% block content %}
<h2>Change Your Password</h2>
<p>Use the form below to change your Password</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

T/log_in/templates/log_in/password_reset_complete.html
{% extends "base/base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h2>Password set</h2>
<p>Your password has been set. You can
    <a href="{% url 'log_in:login' %}">log in now</a></p>
{% endblock %}

T/log_in/templates/log_in/password_reset_confirm.html
{% extends "base/base.html" %}
{% load bootstrap4 %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" value="Change my password">Submit</button>
    {% endbuttons %}
</form>
{% else %}
<p>The password reset link was invalid, possibly because it has
    already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

T/log_in/templates/log_in/password_reset_done.html
{% extends "base/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered
    the address you registered with.</p>
{% endblock %}

T/log_in/templates/log_in/password_reset_email.html
Someone asked for password reset for email {{email}}.Follow the Link below
{{ protocol }}://{{ domain }}{% url "log_in:password_reset_confirm" uidb64=uid token=token %}

T/log_in/templates/log_in/password_reset_form.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% block title %}Reset your password

{% endblock title %}
{% block content %}
<div class="container">
    <h2>Forgotten your Password</h2>
    <p>Enter your email address to obtain a new password</p>
    <form action="" method="post" class="form ">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary" value="send e-mail">Submit</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

T/log_in/templates/log_in/register.html
{% extends "base/base.html" %}
{% load bootstrap4 %}
{% block title %}Registration

{% endblock title %}
{% block content %}

{% if form.errors %}
    
{% endif %}
    
<form action="" method="post" class="form container">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

T/log_in/templates/log_in/register_done.html
{% extends "base/base.html" %}
{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url 'log_in:login' %}">log in</a>.</p>
{% endblock content %}