T/T/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('currency/', include('currency.urls')),
    path('', include('log_in.urls')),
]

T/currency/urls.py
from django.urls import path, re_path
from currency.views import ExchangeAllViews
from currency.views import ExchangeNBUView
from currency.views import ExchangeMonoView
from currency.views import ExchangePrivatView
    
app_name = 'currency'
urlpatterns = [
    # re_path(r'^exchangetimesetup/(?P<time>\d+)/', ExchangeRateController.timer),
    # path('bankrates/', ExchangeRateController.bunk_rates),
    # path('exchangetimesetup/', ExchangeRateController.timer),
    # path('test/', ExchangeRateController.test),
    path('rates/', ExchangeAllViews.as_view()),
    path ('rates/nbu/', ExchangeNBUView.as_view(), name='nbu_view'),
    path ('rates/mono/', ExchangeMonoView.as_view(), name='mono_view'),
    path ('rates/privat/', ExchangePrivatView.as_view(), name='privat_view'),
]

T/log_in/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetDoneView, PasswordResetView,
                                       PasswordResetCompleteView, PasswordResetConfirmView,
                                       PasswordChangeView, PasswordChangeDoneView,
                                       PasswordResetDoneView)
from .views import EditView
from .views import RegisterView
from .views import DashbordView


app_name = 'log_in'

urlpatterns = [
    path('register/', RegisterView.register, name='register'),
    path('edit/', EditView.edit, name='edit'),
    path('dashboard/', DashbordView.dashboard, name='dashboard'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='log_in/logged_out.html'), name='logout'),
    path('password_change/', PasswordChangeView.as_view(
        template_name='log_in/password_change_form.html'), name='password_change'),
    path('password_change/dond/', PasswordChangeDoneView.as_view(template_name='log_in/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(
        template_name='log_in/password_reset_form.html',
        email_template_name='log_in/password_reset_email.html',
        success_url=reverse_lazy('log_in:password_reset_done')), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='log_in/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='/password_reset_confirm.html',
        success_url=reverse_lazy('log_in:login')), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='log_in/password_reset_complete.html'), name='password_reset_complete'),
]

T/log_in/models.py
from django.db import models
from django.conf import settings


class UserRegistrationModel(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

T/log_in/forms.py
from django.contrib.auth.models import User
from django import forms
# from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserRegistrationModel
from django.contrib.auth.forms import PasswordResetForm


class UserRegistration(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

T/log_in/views.py
from django.http import request
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.decorators import login_required

from .forms import UserRegistration, UserEditForm


class DashbordView(View):
    @staticmethod
    @login_required
    def dashboard(request):
        return render(request, 'log_in/dashboard.html', {})

class RegisterView(View):
    @staticmethod
    def register(request):
        if request.method == 'POST':
            form = UserRegistration(request.POST or None)
            if form.is_valid():
                new_user = form.save(commit=False)
                new_user.set_password(
                    form.cleaned_data.get('password')
                )
                new_user.save()
                return render(request, 'log_in/register_done.html')
        else:
            form = UserRegistration()

        context = {
            "form": form
        }
        return render(request, 'log_in/register.html', context=context)

class EditView(View):
    @staticmethod
    @login_required
    def edit(request):
        if request.method == 'POST':
            user_form = UserEditForm(instance=request.user,
                                     data=request.POST)
            if user_form.is_valid():
                user_form.save()
        else:
            user_form = UserEditForm(instance=request.user)
        context = {
            'form': user_form,
        }
        return render(request, 'log_in/edit.html', context=context)

T/log_in/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    
        <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

    {% include "base/navbar.html" %}

    {% block crud_buttons %}
    {% endblock crud_buttons %}

    <div class="container">

        {% block content %}
        {% endblock content %}

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>

</body>

</html>

T/log_in/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'log_in:dashboard' %}">Currency </a>
    {% else  %}
    <a class="navbar-brand" href="/">Authentication </a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:nbu_view' %}">Currency of National Bank</a>
            </li>
            {% for i in buttons_list %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url i.link %}">{{ i.name }}</a>
                 </li>
            {% endfor %}
        </ul>
        {% endif %}
        <span>
            {% if request.user.is_authenticated %}
            <a href="{% url 'log_in:logout' %}" class="btn btn-danger">Logout</a>
            Hello
            @ <i>{{user.username}}</i>
            {% else %}
            <div class="login__left">
                <a href="{% url 'log_in:login' %}" class="btn btn-secondary">Log-in</a>
                <a href="{% url 'log_in:register' %}" class="btn btn-info ">Register</a>
            </div>

            {% endif %}

        </span>
    </div>
</nav>